### PR TITLE
Add missing includes to build on FreeBSD/clang.

### PR DESCRIPTION
**Pull request by uqs**

### CODE REVIEW

**Comment by Flamefire** [comment]
This is wrong. Why did you include vector in uvector?

**Comment by Flow86** [comment]
achja uqs, hast du einen rttr-account? dann kann ich das changelog mit deinen commits verknüpfen

**Comment by Flamefire** [comment]
And can you check if this correction works for you: https://github.com/Return-To-The-Roots/libutil/commit/5b884840e0946ae71d8b67bd9517bbc0841e5bc1

**Comment by uqs** [comment]
Sorry for the mess, your change looks good (can't check at the moment). What I got was clang complaining about not knowing reverse_iterator and const_reverse_iterator and including <vector> *did* get me those definitions. I wasn't aware there's a <iterator> for this.

**Comment by Flamefire** [comment]
The main goal is: Include as few headers as possible. It also helps to include the headers in the order of their dependencies.
So own headers goes first, then library headers, and last standard headers-
About finding the correct include: Google e.g. "reverse_iterator". 1st or 2nd hit is http://www.cplusplus.com/reference/iterator/reverse_iterator/ which tells you the include file in the top right corner "<iterator>"

**Comment by uqs** [comment]
My Google-fu clearly is weak :/
Thanks for the pointers, will consult cplusplus.com more often!

**Comment by lweberk** [comment]
@Flamefire regarding the ordering, exactly but the other way around? From global to local, from extern to intern. sdlib, 3party, own-libs, own-sources.

**Comment by Flamefire** [comment]
You can also do this, but we (at work) use the other way round. This is more consistent. E.g. in a cpp file you first include the corresponding header, then the others.
Using the system libs last reveals  where you forgot to include a header in any header file.

For example (fictive, just using our names) in libsiedler2 you have an ArchivItem that contains a vector, but does not include "< vector >" in the header. In the cpp file you do that. You also include ArchivItem.h in another cpp file but used "#include <vector>" before including ArchivItem.h. Everything still works...
Later you use that library in s25client and include the header. You are not using any vector in the file (that included ArchivItem.h) but your code won't compile, because it can't find std::vector. This would have been noticed, if you always include the system headers last. It basicly forces you, to include (or forward declare) all headers/types on use.

**Comment by Flow86** [comment]
@Flamefire: we do that at work the same way (mostly at least), cpp file includes its header first, then everything else.

**Comment by uqs** [comment]
@Flow86: got no login yet, I want to get this running under FreeBSD first to check it out (how hard can it be?) :)

**Pull request merged**
