### PR TITLE
Update files.h

### PR DESCRIPTION
**Pull request by stefson**
fix typos in comments

### CODE REVIEW

**Comment by Flamefire** [comment]
Can you please squash this and #14 into one PR? This are very related changes so 2 commits would be enough. One can even put both changes into 1 commit and name it "umlaut-fixes" or so.
BTW: For the future, translate these strings to English. We want to have as much as possible in English, so instead of replacing wrong German by right German and then by English replace it by English directly. If you want, you can do it for your current PRs, if not, I'lll just merge them.

**Comment by stefson** [comment]
I don't know how to squash these two edits I made into one single pull request. The webinterface is really confusing, whilst it wouldn't be much of a big deal to provide a patch with the output of git diff.

**Comment by Flamefire** [comment]
It is actually pretty simple: For each set of (very) related changes start a new branch on top of the current master. Add your commits to the branch and once your changes are tested, add a PR so your whole changeset (the branch) is merged into the master. If the master has changed in the meantime, it is a good idea to do a "rebase" on top of the new master.
After your PR is opened, any additions (e.g. after feedback) can be added to the branch (just commit and push to your same remote branch) then they will automaticly show up in the PR.

In this case try this: Checkout this branch (patch-2), cherry-pick the commit from patch-1 (1e16388) and push it. Then you can delete the patch-1 branch and close the other PR. If you don't want to try it it's fine. But it is a good exercise if you want to learn git. I can also recommend using smartGit for linux or TortoiseGit for windows (which is IMO the best way for using git)

Patches are the "old" way. PRs are much easier to handle. Once you get used to the checkout/create branch -> commit -> push workflow you'll enjoy this :) E.g. sometimes a PR contains small issues (typos, C&P errors, some ideas from others that should be included, ...) By using the PR system the owner can just add the changes and commit it to the branch. It will automaticly show up here and one also has the history with line-annotated discussions etc.

**Comment by stefson** [comment]
I tried it but this is way too complicated. I'm perfectly fine with sending in patches the old way, so please provide me with an email adress for sending to. thank you.

**Comment by Flamefire** [comment]
Sorry but patches are to much work for the maintainers. So PRs only. Try a few tutorials and you can also find some help in IRC if you get stuck.
Bonus: Git and github is used in quite some companies this days. So learning it will also help you in "real life"

**Comment by stefson** [comment]
in which irc channel may I get help?

**Comment by Flamefire** [comment]
http://www.siedler25.org/index.php?com=dynamic&mod=3

**Pull request closed without merging**
